# Generated by Django 5.2.1 on 2025-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_profession_alter_profile_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhaar Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nominee',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nominee Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Occupation Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
