# Generated by Django 5.2.1 on 2025-10-26 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_linkedaccount_externaltransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedaccount',
            name='user',
        ),
        migrations.CreateModel(
            name='AccountIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Bank', 'Bank Account'), ('Credit Card', 'Credit Card'), ('Wallet', 'Digital Wallet')], max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_linked', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ExternalTransaction',
        ),
        migrations.DeleteModel(
            name='LinkedAccount',
        ),
    ]
