# Generated by Django 5.2.1 on 2025-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_investmentsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
