# Generated by Django 5.2.1 on 2025-11-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_profile_birthday_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsuggestion',
            name='goal_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentsuggestion',
            name='current_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentsuggestion',
            name='target_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentsuggestion',
            name='due_date',
            field=models.DateField(default='2025-11-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentsuggestion',
            name='suggestion_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
