# Generated by Django 5.2.1 on 2025-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_investmentsuggestion_suggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
