# Generated by Django 5.2.1 on 2025-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_financialgoal_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of shares/units (for stocks/MF)', max_digits=10, null=True),
        ),
    ]
